Experiment_name: sibi_modified_ShiftGCN_mod_2_joint_n_5_kfold
# feeder
feeder: feeders.feeder_hsd.Feeder
data_path: ./data/augmented_recalculate_normalized
test_feeder_args:
  # data_path: ./data/hsd/val_data_joint.npy
  # label_path: ./data/hsd/val_label.pkl
  debug: False

# model
model: model.shift_gcn.Model
model_args:
  num_class: 50 # 400
  num_person: 1
  num_point: 115
  method: 'modified'
  weight: 2
  graph: graph.skeleton_with_mouth.SkeletonWithMouth
  graph_args:
    labeling_mode: 'spatial'

n_splits: 5
# test
phase: full_test
device: [0]
test_batch_size: 5
weights: ./save_models/sibi_modified_ShiftGCN_mod_2_joint_n_5_kfold_fold_5-29-14400.pt

work_dir: ./work_dir/sibi_modified_ShiftGCN_mod_2_joint_n_5_kfold_fold_5
model_saved_name: ./save_models/sibi_modified_ShiftGCN_mod_2_joint_n_5_kfold_fold_5
save_score: True
num_worker: 1